#!/bin/sh
/bin/rm -f upload/* 2> /dev/null
/bin/rm -f upload/thumbnail/* 2> /dev/null
cd db
echo "delete from chat_log;" | sqlite3 chat2.sqlite
cd ..
myhost=`hostname`
echo $myhost
if [ $myhost = 'pegasus.west.home' ]; then
chown apache.apache -R *
else
chown www-data.www-data -R *
chmod ug+w -R *
fi
