#!/bin/sh
#cp */resize/*.png .
/bin/ls *.png > files.json.1
cat files.json.1 | sed -e 's/^/["/' > files.json.2
cat files.json.2 | sed -e 's/$/"],/' > files.json.3
echo "["
cat files.json.3 | sed -e '$s/,$//'
echo "]"
